---
name: 'RushJS Helper'
author: Martin Reynolds
description: 'Run rush install if required and manage caching for optimal performance and incremental builds.'
runs:
  using: 'node12'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: 'success()'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  package-manager:
    description: 'Package manager used by the project'
    required: false
    default: 'pnpm'
  build:
    description: 'Run rush build'
    required: false
    default: false
