#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm test

# Update test lock file to facilitate testing workflows
echo "test: '$(date)'" > __tests__/data/common/config/rush/pnpm-lock.yaml
git add __tests__/data/common/config/rush/pnpm-lock.yaml

# Update test rush.json to facilitate testing workflows
echo "{ \"test\": \"$(date)\" }" > __tests__/data/rush.json
git add __tests__/data/rush.json
