#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm test
echo "test: '$(date)'" > common/config/rush/pnpm-lock.yaml
git add common/config/rush/pnpm-lock.yaml

echo "{ \"test\": \"$(date)\" }" > rush.json
git add rush.json
