name: Repository Config Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/repository/**'

jobs:
  validate-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install yaml
      - uses: actions/github-script@v6
        name: Run scripts
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const yaml = require('yaml')

            console.log('1')
            const repo = "${{ github.repository }}".split('/')[1]

            console.log('2')
            const owner = "${{ github.repository_owner }}"

            console.log('3')
            const userFile = ".github/repository/users.yml"

            console.log('4')
            const script = require('${{ github.workspace }}/.github/repository/src/check-pr.js')
            const result = await script({github, context, owner, repo, userFile, yaml})
            console.log(``)
            console.log(`End of workflow step`)
