name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test pnpm
        uses: ./
      - name: Test npm
        uses: ./
        with:
          package-manager: npm
      - name: Test yarn
        uses: ./
        with:
          package-manager: yarn
